"""empty message

Revision ID: 46bd1211368a
Revises: 
Create Date: 2021-08-17 12:55:55.500385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bd1211368a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.add_column('entries', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('entries', sa.Column('abl_since_last', sa.Float(), nullable=True))
    op.add_column('entries', sa.Column('abl_since_oct', sa.Float(), nullable=True))
    op.add_column('entries', sa.Column('abl_since_drilled', sa.Float(), nullable=True))
    op.alter_column('entries', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_timestamp'), 'entries', ['timestamp'], unique=False)
    op.drop_column('entries', 'abl_oct')
    op.alter_column('stakes', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_stakes_id'), 'stakes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakes_id'), table_name='stakes')
    op.alter_column('stakes', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.add_column('entries', sa.Column('abl_oct', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_entries_timestamp'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.alter_column('entries', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('entries', 'abl_since_drilled')
    op.drop_column('entries', 'abl_since_oct')
    op.drop_column('entries', 'abl_since_last')
    op.drop_column('entries', 'timestamp')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
